import mongoose from "mongoose";

const ProductSchema = new mongoose.Schema(
  {
    name: { type: String, required: true, trim: true },

    // Must match controller → categoryId
    categoryId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Category",
      required: true,
    },

    salePrice: { type: Number, required: true },
    costPrice: { type: Number, default: 0 },
    wholesalePrice: { type: Number, default: 0 },

    stock: { type: Number, default: 0 },

    // Codes generated by backend
    sku: { type: String },
    barcode: { type: String, unique: true, sparse: true },
    productNumber: { type: String },

    hsn: { type: String, default: "" },

    photo: { type: String, default: null },

    active: { type: Boolean, default: true },
  },
  { timestamps: true }
);

export default mongoose.model("Product", ProductSchema);
